--------------------------------------------------------
--  Fichier créé - jeudi-janvier-07-2021   
--------------------------------------------------------
DROP TABLE "HSOUNA"."AMENDE";
DROP TABLE "HSOUNA"."CERTIFDECES";
DROP TABLE "HSOUNA"."CITOYENT";
DROP TABLE "HSOUNA"."COMMERCIALE";
DROP TABLE "HSOUNA"."DEPARTEMENT";
DROP TABLE "HSOUNA"."EMPLOYEE";
DROP TABLE "HSOUNA"."PERMISCONSTRUCTIONN";
DROP TABLE "HSOUNA"."TABLE1";
DROP TABLE "HSOUNA"."TABLE2";
DROP TABLE "HSOUNA"."VEHICULE";
--------------------------------------------------------
--  DDL for Table AMENDE
--------------------------------------------------------

  CREATE TABLE "HSOUNA"."AMENDE" 
   (	"CIN_A" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"MONTANT" VARCHAR2(20 BYTE), 
	"DATEA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CERTIFDECES
--------------------------------------------------------

  CREATE TABLE "HSOUNA"."CERTIFDECES" 
   (	"CIN_D" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATEDECES" VARCHAR2(20 BYTE), 
	"LIEU" VARCHAR2(20 BYTE), 
	"ETATMATRIM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CITOYENT
--------------------------------------------------------

  CREATE TABLE "HSOUNA"."CITOYENT" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATE_NAISSANCE" VARCHAR2(20 BYTE), 
	"LIEU" VARCHAR2(20 BYTE), 
	"AGE" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(20 BYTE), 
	"NUM_TELPH" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(20 BYTE), 
	"PROFESSION" VARCHAR2(20 BYTE), 
	"VILLE" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"CODE_POSTALE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMERCIALE
--------------------------------------------------------

  CREATE TABLE "HSOUNA"."COMMERCIALE" 
   (	"CIN_CO" VARCHAR2(20 BYTE), 
	"CNSS" VARCHAR2(20 BYTE), 
	"FISCALE" VARCHAR2(20 BYTE), 
	"SECTEUR_DACTIVITE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPARTEMENT
--------------------------------------------------------

  CREATE TABLE "HSOUNA"."DEPARTEMENT" 
   (	"ID_DEP" VARCHAR2(20 BYTE), 
	"NOM_DEP" VARCHAR2(20 BYTE), 
	"NBR_DEP" VARCHAR2(20 BYTE), 
	"BUDGET" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "HSOUNA"."EMPLOYEE" 
   (	"CIN_E" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NUME" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERMISCONSTRUCTIONN
--------------------------------------------------------

  CREATE TABLE "HSOUNA"."PERMISCONSTRUCTIONN" 
   (	"CIN_P" VARCHAR2(20 BYTE), 
	"LIEU" VARCHAR2(20 BYTE), 
	"CODEPOSTALE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TABLE1
--------------------------------------------------------

  CREATE TABLE "HSOUNA"."TABLE1" 
   (	"CINM" VARCHAR2(20 BYTE), 
	"NOMPRENOMM" VARCHAR2(20 BYTE), 
	"METIERM" VARCHAR2(20 BYTE), 
	"NOMPRENOMP" VARCHAR2(20 BYTE), 
	"METIERP" VARCHAR2(20 BYTE), 
	"CINP" VARCHAR2(20 BYTE), 
	"DATEMARIAGE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TABLE2
--------------------------------------------------------

  CREATE TABLE "HSOUNA"."TABLE2" 
   (	"MATRICULE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"COULEUR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VEHICULE
--------------------------------------------------------

  CREATE TABLE "HSOUNA"."VEHICULE" 
   (	"TYPE" VARCHAR2(20 BYTE), 
	"MARQUE" VARCHAR2(20 BYTE), 
	"MATRICULE" VARCHAR2(20 BYTE), 
	"PUISSANCE" VARCHAR2(20 BYTE), 
	"ENERGIE" VARCHAR2(20 BYTE), 
	"DATES" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HSOUNA.AMENDE
SET DEFINE OFF;
Insert into HSOUNA.AMENDE (CIN_A,NOM,PRENOM,TYPE,MONTANT,DATEA) values ('9999','rrrrrr','fghj','fghj','5555','rrrrrr');
Insert into HSOUNA.AMENDE (CIN_A,NOM,PRENOM,TYPE,MONTANT,DATEA) values ('5555','rrrrrr','fghj','fghj','5555','ghjk');
REM INSERTING into HSOUNA.CERTIFDECES
SET DEFINE OFF;
Insert into HSOUNA.CERTIFDECES (CIN_D,NOM,PRENOM,DATEDECES,LIEU,ETATMATRIM) values ('1111','uuuuu','dfgh','sam. janv. 1 2000','sdfgh','Voeuf(ve)');
Insert into HSOUNA.CERTIFDECES (CIN_D,NOM,PRENOM,DATEDECES,LIEU,ETATMATRIM) values ('444444','ppppp','yyyyy','sam. janv. 1 2000','yyyyyy','CÃ©libataire');
REM INSERTING into HSOUNA.CITOYENT
SET DEFINE OFF;
Insert into HSOUNA.CITOYENT (CIN,NOM,PRENOM,DATE_NAISSANCE,LIEU,AGE,SEXE,NUM_TELPH,MAIL,PROFESSION,VILLE,ADRESSE,CODE_POSTALE) values ('20120','thegt','eheeheh','sam. janv. 1 2000',null,'0','Homme ','0',null,null,'zeze',null,'0');
Insert into HSOUNA.CITOYENT (CIN,NOM,PRENOM,DATE_NAISSANCE,LIEU,AGE,SEXE,NUM_TELPH,MAIL,PROFESSION,VILLE,ADRESSE,CODE_POSTALE) values ('14111225','aaamaamm','aaaaa','sam. janv. 1 2000','zaeze','8','Femme','41254125',null,'azeaz',null,'zeze','1452');
REM INSERTING into HSOUNA.COMMERCIALE
SET DEFINE OFF;
Insert into HSOUNA.COMMERCIALE (CIN_CO,CNSS,FISCALE,SECTEUR_DACTIVITE) values ('55555555','2365','7445','aaee');
Insert into HSOUNA.COMMERCIALE (CIN_CO,CNSS,FISCALE,SECTEUR_DACTIVITE) values ('44444444','2222','7757','dfdfgf');
REM INSERTING into HSOUNA.DEPARTEMENT
SET DEFINE OFF;
Insert into HSOUNA.DEPARTEMENT (ID_DEP,NOM_DEP,NBR_DEP,BUDGET) values ('11111','bbbb','41','50');
Insert into HSOUNA.DEPARTEMENT (ID_DEP,NOM_DEP,NBR_DEP,BUDGET) values ('568','aaa','555','30');
Insert into HSOUNA.DEPARTEMENT (ID_DEP,NOM_DEP,NBR_DEP,BUDGET) values ('8520','aaaa','20','20');
REM INSERTING into HSOUNA.EMPLOYEE
SET DEFINE OFF;
Insert into HSOUNA.EMPLOYEE (CIN_E,NOM,PRENOM,NUME,ADRESSE) values ('145','bbb','bbbb','7454','aaaaa');
Insert into HSOUNA.EMPLOYEE (CIN_E,NOM,PRENOM,NUME,ADRESSE) values ('147','aaa','aaa','13365','aaaa');
Insert into HSOUNA.EMPLOYEE (CIN_E,NOM,PRENOM,NUME,ADRESSE) values ('202','zzzz','cccc','25852','aaaa');
REM INSERTING into HSOUNA.PERMISCONSTRUCTIONN
SET DEFINE OFF;
Insert into HSOUNA.PERMISCONSTRUCTIONN (CIN_P,LIEU,CODEPOSTALE) values ('741','aaaa','741');
Insert into HSOUNA.PERMISCONSTRUCTIONN (CIN_P,LIEU,CODEPOSTALE) values ('74111','aaaabb','741');
Insert into HSOUNA.PERMISCONSTRUCTIONN (CIN_P,LIEU,CODEPOSTALE) values ('22','aaaabb','741');
REM INSERTING into HSOUNA.TABLE1
SET DEFINE OFF;
Insert into HSOUNA.TABLE1 (CINM,NOMPRENOMM,METIERM,NOMPRENOMP,METIERP,CINP,DATEMARIAGE) values ('5555555','kkk','aaaaa','aaaaaa','kjggg','2222222','aaaaa');
Insert into HSOUNA.TABLE1 (CINM,NOMPRENOMM,METIERM,NOMPRENOMP,METIERP,CINP,DATEMARIAGE) values ('5555555','kkk','aaaaa','aaaaaa','kjggg','2222222','ccccccc');
Insert into HSOUNA.TABLE1 (CINM,NOMPRENOMM,METIERM,NOMPRENOMP,METIERP,CINP,DATEMARIAGE) values ('66555','aaaa','aaa','aaa','aaaa','55555','5555');
Insert into HSOUNA.TABLE1 (CINM,NOMPRENOMM,METIERM,NOMPRENOMP,METIERP,CINP,DATEMARIAGE) values ('12345678','aaaaaaaaa','aaaaa','ahmed','aaaaaaa','12302584','14aaaa');
REM INSERTING into HSOUNA.TABLE2
SET DEFINE OFF;
Insert into HSOUNA.TABLE2 (MATRICULE,TYPE,COULEUR) values (null,null,null);
Insert into HSOUNA.TABLE2 (MATRICULE,TYPE,COULEUR) values (null,null,null);
Insert into HSOUNA.TABLE2 (MATRICULE,TYPE,COULEUR) values (null,null,null);
Insert into HSOUNA.TABLE2 (MATRICULE,TYPE,COULEUR) values ('ddddd','dddd','ssss');
Insert into HSOUNA.TABLE2 (MATRICULE,TYPE,COULEUR) values ('1236','dddd','ssss');
Insert into HSOUNA.TABLE2 (MATRICULE,TYPE,COULEUR) values ('85862368','J76J','ssss');
Insert into HSOUNA.TABLE2 (MATRICULE,TYPE,COULEUR) values ('25828628','tttt','tttt');
REM INSERTING into HSOUNA.VEHICULE
SET DEFINE OFF;
Insert into HSOUNA.VEHICULE (TYPE,MARQUE,MATRICULE,PUISSANCE,ENERGIE,DATES) values ('aaa',null,null,null,null,null);
Insert into HSOUNA.VEHICULE (TYPE,MARQUE,MATRICULE,PUISSANCE,ENERGIE,DATES) values ('1223',null,null,null,null,null);
Insert into HSOUNA.VEHICULE (TYPE,MARQUE,MATRICULE,PUISSANCE,ENERGIE,DATES) values ('1223','aaa',null,null,null,null);
--------------------------------------------------------
--  DDL for Index AMENDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HSOUNA"."AMENDE_PK" ON "HSOUNA"."AMENDE" ("CIN_A") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CERTIFDECES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HSOUNA"."CERTIFDECES_PK" ON "HSOUNA"."CERTIFDECES" ("CIN_D") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CITOYENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HSOUNA"."CITOYENT_PK" ON "HSOUNA"."CITOYENT" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMERCIALE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HSOUNA"."COMMERCIALE_PK" ON "HSOUNA"."COMMERCIALE" ("CIN_CO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPARTEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HSOUNA"."DEPARTEMENT_PK" ON "HSOUNA"."DEPARTEMENT" ("ID_DEP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HSOUNA"."EMPLOYEE_PK" ON "HSOUNA"."EMPLOYEE" ("CIN_E") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERMISCONSTRUCTIONN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HSOUNA"."PERMISCONSTRUCTIONN_PK" ON "HSOUNA"."PERMISCONSTRUCTIONN" ("CIN_P") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AMENDE
--------------------------------------------------------

  ALTER TABLE "HSOUNA"."AMENDE" ADD CONSTRAINT "AMENDE_PK" PRIMARY KEY ("CIN_A")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HSOUNA"."AMENDE" MODIFY ("CIN_A" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CERTIFDECES
--------------------------------------------------------

  ALTER TABLE "HSOUNA"."CERTIFDECES" MODIFY ("CIN_D" NOT NULL ENABLE);
  ALTER TABLE "HSOUNA"."CERTIFDECES" ADD CONSTRAINT "CERTIFDECES_PK" PRIMARY KEY ("CIN_D")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CITOYENT
--------------------------------------------------------

  ALTER TABLE "HSOUNA"."CITOYENT" ADD CONSTRAINT "CITOYENT_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HSOUNA"."CITOYENT" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMERCIALE
--------------------------------------------------------

  ALTER TABLE "HSOUNA"."COMMERCIALE" ADD CONSTRAINT "COMMERCIALE_PK" PRIMARY KEY ("CIN_CO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HSOUNA"."COMMERCIALE" MODIFY ("CIN_CO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTEMENT
--------------------------------------------------------

  ALTER TABLE "HSOUNA"."DEPARTEMENT" MODIFY ("ID_DEP" NOT NULL ENABLE);
  ALTER TABLE "HSOUNA"."DEPARTEMENT" ADD CONSTRAINT "DEPARTEMENT_PK" PRIMARY KEY ("ID_DEP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "HSOUNA"."EMPLOYEE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "HSOUNA"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("CIN_E")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HSOUNA"."EMPLOYEE" MODIFY ("CIN_E" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERMISCONSTRUCTIONN
--------------------------------------------------------

  ALTER TABLE "HSOUNA"."PERMISCONSTRUCTIONN" ADD CONSTRAINT "PERMISCONSTRUCTIONN_PK" PRIMARY KEY ("CIN_P")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HSOUNA"."PERMISCONSTRUCTIONN" MODIFY ("CIN_P" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TABLE1
--------------------------------------------------------

  ALTER TABLE "HSOUNA"."TABLE1" MODIFY ("CINM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VEHICULE
--------------------------------------------------------

  ALTER TABLE "HSOUNA"."VEHICULE" MODIFY ("TYPE" NOT NULL ENABLE);
